#!/usr/bin/env python3
"""
Extract source code files from Manus handoff markdown documents.
Parses code blocks and writes them to web/ directory structure.
"""

import re
import os
from pathlib import Path

BASE = Path(__file__).resolve().parent
MANUS_DIR = BASE / "Manus MD Files"
WEB_DIR = BASE / "web"

# Skip these directories (auto-generated by Manus platform)
SKIP_DIRS = ["_core/", "components/ui/"]

# Handoff files to process in order
HANDOFF_FILES = [
    "StrainScout MD — Complete Source Code Handoff for Claude (1).md",
    "handoff_01_server_layer.md",
    "handoff_02_schema_and_config.md",
    "handoff_03_frontend_core.md",
    "handoff_05_frontend_pages_1.md",
    "handoff_06_frontend_pages_2.md",
    "handoff_07_test_files.md",
]

# Also check for component file
EXTRA_FILES = [
    "handoff_04_frontend_components.md",
]


def extract_files_from_markdown(md_path: Path) -> list[tuple[str, str]]:
    """Extract (filepath, code) pairs from a markdown file."""
    with open(md_path, encoding="utf-8") as f:
        content = f.read()

    files = []

    # Pattern 1: ## N. `filepath` followed by ```lang\ncode\n```
    # This is the most common pattern in handoff docs
    pattern1 = re.compile(
        r'##\s+\d+\.\s+`([^`]+)`.*?\n'  # ## N. `filepath`
        r'.*?'  # optional description lines
        r'```\w*\n'  # opening code fence
        r'(.*?)'  # code content
        r'\n```',  # closing code fence
        re.DOTALL
    )

    # Pattern 2: ### filepath followed by code block
    pattern2 = re.compile(
        r'###\s+((?:client|server|shared|drizzle|tests?)[^\n]+\.(?:ts|tsx|js|jsx|json|css|html))\s*\n'
        r'.*?'
        r'```\w*\n'
        r'(.*?)'
        r'\n```',
        re.DOTALL
    )

    # Pattern 3: **File:** `filepath` or similar header with code
    pattern3 = re.compile(
        r'(?:\*\*(?:File|Path):\*\*\s*`([^`]+)`|'
        r'(?:^|\n)#+\s+(?:File:\s*)?`([^`]+)`)'
        r'.*?'
        r'```\w*\n'
        r'(.*?)'
        r'\n```',
        re.DOTALL
    )

    # Use a combined approach: find all code blocks and look backwards for file path
    code_blocks = list(re.finditer(r'```(\w*)\n(.*?)\n```', content, re.DOTALL))

    for match in code_blocks:
        lang = match.group(1)
        code = match.group(2)

        # Skip non-code blocks
        if lang in ('', 'bash', 'sh', 'shell', 'sql', 'text', 'txt', 'md', 'markdown', 'diff', 'log'):
            # Still check if it's a config file
            if lang not in ('', 'bash', 'sh', 'shell', 'sql', 'text', 'txt', 'md', 'markdown', 'diff', 'log'):
                continue

        # Look backwards from this code block for a file path
        before = content[:match.start()]

        # Try to find file path in preceding lines
        filepath = None

        # Look for ## N. `filepath` pattern (most common)
        m = re.search(r'##\s+\d+\.\s+`([^`]+\.(?:ts|tsx|js|jsx|json|css|html))`[^\n]*$', before, re.MULTILINE)
        if m:
            # Check this is the closest header to our code block
            between = before[m.end():]
            if '```' not in between:  # No other code block between header and this one
                filepath = m.group(1)

        if not filepath:
            # Try ### filepath pattern
            m = re.search(r'###\s+`?([^\n`]+\.(?:ts|tsx|js|jsx|json|css|html))`?\s*$', before, re.MULTILINE)
            if m:
                between = before[m.end():]
                if '```' not in between:
                    filepath = m.group(1).strip()

        if not filepath:
            # Try **Lines:** N pattern after ## header
            m = re.search(r'##\s+\d+\.\s+`([^`]+)`.*?\*\*Lines:\*\*', before, re.DOTALL)
            if m:
                between = before[m.end():]
                if '```' not in between:
                    filepath = m.group(1)

        if filepath:
            # Clean the filepath
            filepath = filepath.strip().strip('`').strip()

            # Skip _core and ui directories
            if any(skip in filepath for skip in SKIP_DIRS):
                continue

            # Only process actual source files
            if filepath.endswith(('.ts', '.tsx', '.js', '.jsx', '.json', '.css', '.html')):
                files.append((filepath, code))

    return files


def write_extracted_files(files: list[tuple[str, str]]):
    """Write extracted files to the web/ directory."""
    written = 0
    skipped = 0

    for filepath, code in files:
        # Skip _core and ui directories
        if any(skip in filepath for skip in SKIP_DIRS):
            skipped += 1
            continue

        out_path = WEB_DIR / filepath
        out_path.parent.mkdir(parents=True, exist_ok=True)

        # Don't overwrite existing files (in case of duplicates across handoff docs)
        if out_path.exists():
            existing_size = out_path.stat().st_size
            new_size = len(code.encode('utf-8'))
            # Keep the larger version
            if new_size <= existing_size:
                print(f"  SKIP (exists, {existing_size}B >= {new_size}B): {filepath}")
                skipped += 1
                continue
            else:
                print(f"  UPDATE (larger): {filepath} ({existing_size}B → {new_size}B)")

        with open(out_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(code)
            if not code.endswith("\n"):
                f.write("\n")

        written += 1
        print(f"  WRITE: {filepath} ({len(code)} chars)")

    return written, skipped


def main():
    print("=" * 70)
    print("EXTRACTING SOURCE CODE FROM MANUS HANDOFF DOCS")
    print("=" * 70)
    print(f"Source: {MANUS_DIR}")
    print(f"Output: {WEB_DIR}")
    print()

    all_files = []

    for filename in HANDOFF_FILES + EXTRA_FILES:
        md_path = MANUS_DIR / filename
        if not md_path.exists():
            print(f"SKIP (not found): {filename}")
            continue

        print(f"Processing: {filename}")
        files = extract_files_from_markdown(md_path)
        print(f"  Found {len(files)} code blocks with file paths")

        for fp, code in files:
            print(f"    {fp} ({len(code)} chars)")

        all_files.extend(files)

    print()
    print(f"Total files found: {len(all_files)}")
    print()

    written, skipped = write_extracted_files(all_files)

    print()
    print(f"Written: {written}")
    print(f"Skipped: {skipped}")
    print(f"Total: {written + skipped}")


if __name__ == "__main__":
    main()
