import * as React from "react";
import * as P from "@radix-ui/react-dropdown-menu";
import { cn } from "@/lib/utils";
const DropdownMenu=P.Root;const DropdownMenuTrigger=P.Trigger;const DropdownMenuGroup=P.Group;const DropdownMenuSub=P.Sub;const DropdownMenuRadioGroup=P.RadioGroup;
const DropdownMenuContent=React.forwardRef<any,any>(({className,sideOffset=4,...p},ref)=>(<P.Portal><P.Content ref={ref} sideOffset={sideOffset} className={cn("z-50 min-w-[8rem] overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-md",className)}{...p}/></P.Portal>));DropdownMenuContent.displayName="DropdownMenuContent";
const DropdownMenuItem=React.forwardRef<any,any>(({className,...p},ref)=><P.Item ref={ref} className={cn("relative flex cursor-default select-none items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-none focus:bg-accent",className)}{...p}/>);DropdownMenuItem.displayName="DropdownMenuItem";
const DropdownMenuLabel=React.forwardRef<any,any>(({className,...p},ref)=><P.Label ref={ref} className={cn("px-2 py-1.5 text-sm font-semibold",className)}{...p}/>);DropdownMenuLabel.displayName="DropdownMenuLabel";
const DropdownMenuSeparator=React.forwardRef<any,any>(({className,...p},ref)=><P.Separator ref={ref} className={cn("-mx-1 my-1 h-px bg-muted",className)}{...p}/>);DropdownMenuSeparator.displayName="DropdownMenuSeparator";
const DropdownMenuCheckboxItem=React.forwardRef<any,any>(({className,children,checked,...p},ref)=><P.CheckboxItem ref={ref} className={cn("relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none focus:bg-accent",className)} checked={checked}{...p}>{children}</P.CheckboxItem>);DropdownMenuCheckboxItem.displayName="DropdownMenuCheckboxItem";
export{DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuCheckboxItem,DropdownMenuLabel,DropdownMenuSeparator,DropdownMenuGroup,DropdownMenuSub,DropdownMenuRadioGroup};
